name: Typecheck

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  typecheck:
    name: Typecheck code with mypy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip mypy
          python -m pip install -r ./requirements.txt

      - name: Typecheck code with mypy
        run: mypy adb test
